# Generated by Django 3.1.5 on 2021-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(choices=[('START', 'START'), ('STOP', 'STOP'), ('REPORT', 'REPORT')], default='START', max_length=30)),
                ('servers', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
