# Generated by Django 3.1.5 on 2021-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='servers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
