# Generated by Django 3.1.5 on 2021-01-25 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
